# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

builds:
  - id: claude-status
    main: ./cmd/claude-status
    binary: claude-status
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}

archives:
  - id: default
    formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

changelog:
  use: github
  sort: asc

release:
  github:
    owner: kostyay
    name: claude-status
  draft: false
  prerelease: auto
